clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: system
    static_configs:
      - labels:
          __path__: "/containers/*/*.log"
    pipeline_stages:
      - json:
          expressions:
            service: attrs.tag
            log: log
            timestamp: time
      - json:
          source: log
          expressions:
            level: level
            message: message
            timestamp: timestamp
            logger_name: logger_name
            stack_trace: stack_trace
            thread_name: thread_name
      - labels:
          level:
          service:
      - template:
          source: stack_trace
          template: '{{if .Value }} {{- " | Stack Trace: " -}}{{- .Value -}} {{else}} {{- " " -}} {{end}}'
      - template:
          source: line
          template: "{{ ToUpper .level }} {{ .logger_name }} [{{ .thread_name }}] {{ .message }} {{- .stack_trace -}}"
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: line