{
 "title": "Game",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Request Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum[30s])) by (uri)\n/\nsum(irate(http_server_requests_seconds_count[30s])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Current Games",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "game_games_total", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Games Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(game_games_won_total[30s])",
     "legendFormat": "Won"
    },
    {
     "expr": "rate(game_games_lost_total[30s])",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "Guesses Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(game_guesses_correct_total[30s])",
     "legendFormat": "Correct"
    },
    {
     "expr": "rate(game_guesses_incorrect_total[30s])",
     "legendFormat": "Incorrect"
    }
   ]
  }
 ]
}